global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'notification-core'
    static_configs:
      - targets: ['notification-core:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'provider-email'
    static_configs:
      - targets: ['provider-email:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'provider-push'
    static_configs:
      - targets: ['provider-push:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'provider-sms'
    static_configs:
      - targets: ['provider-sms:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']
    metrics_path: '/actuator/prometheus'